pipeline:
  name: tensorflow pr pipeline chaining
  identifier: tensorflow_pr_pipeline_chaining
  projectIdentifier: parson
  orgIdentifier: SE_Sandbox
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "hello world"
