name: Build manylinux2014 aarch64 PyPI wheel

on:
  push:
    tags:
    - v2.*
    branches:
    - r2.9-arm
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
  - cron: "30 8 * * *"

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        pyver: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Run python wheel build script
      shell: bash
      run: |
        CI_DOCKER_BUILD_EXTRA_PARAMS='--build-arg py_major_minor_version=${{ matrix.pyver }}' \
        ./tensorflow/tools/ci_build/ci_build.sh cpu.arm64 bash tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_pip.sh
